# Generated by Django 5.2.2 on 2025-06-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='desciption',
            new_name='description',
        ),
    ]
